services:
  supanova-maintenance:
    image: jdgarner/supanova-maintenance:latest
    container_name: supanova-maintenance
    env_file: .env
    network_mode: host
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "{{.Name}}"
        fluentd-async: "true"
        fluentd-max-retries: "5"
